sudo: required

env:
  matrix:
    - DOCKERFILE="5.3"
    - DOCKERFILE="5.5"
    - DOCKERFILE="5.6"
    - DOCKERFILE="7.0"

services:
  - docker

before_script:
  - docker version

script:
  - docker build -t ${DOCKERFILE} ./${DOCKERFILE}

after_script:
  - docker images
