sudo: required

services:
  - docker

env:
  matrix:
    - DOCKERFILE="5.6"

before_script:
  - docker version

script:
  - docker build -t ${DOCKERFILE} ./${DOCKERFILE}

after_script:
  - docker images
