version: '2'
services:
  php:
    container_name: php71
    image: ryublacknd/php:7.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./mysql_data:/var/lib/mysql
