version: '2'
services:
  php:
    container_name: php53
    image: ryublacknd/php:5.3
    ports:
      - "80:80"
      - "443:443"
      - "1080:1080"
    volumes:
      - ./html:/var/www/html
      - ./mysql_data:/var/lib/mysql
