version: '2'
services:
  php:
    container_name: php54
    image: ryublacknd/php:5.4
    ports:
      - "80:80"
      - "443:443"
      - "1080:1080"
    volumes:
      - ./html:/var/www/html
      - ./mysql_data:/var/lib/mysql
