version: '2'
services:
  php:
    container_name: php54
    image: ryublacknd/php:5.4
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./html:/var/www/html
      - ./mysql_data:/var/lib/mysql
